#!/bin/bash
# java8 fast switching to / from java 11 ubuntu-debian based
rm -rf /etc/alternatives/javac
rm -rf /etc/alternatives/java
ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java /etc/alternatives/java
ln -s /usr/lib/jvm/java-8-openjdk-amd64/bin/javac /etc/alternatives/javac 
java -version
javac -version
