#!/bin/bash
#java 11 switch
rm -rf /etc/alternatives/javac
rm -rf /etc/alternatives/java
ln -s /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-5.fc34.x86_64/bin/java  /etc/alternatives/java
ln -s /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-5.fc34.x86_64/bin/javac  /etc/alternatives/javac
java -version
javac -version
