#!/bin/bash
#
#java 11 switch ubuntu/debian based systems
rm -rf /etc/alternatives/javac
rm -rf /etc/alternatives/java
ln -s /usr/lib/jvm/java-11-openjdk-amd64/bin/java  /etc/alternatives/java
ln -s /usr/lib/jvm/java-11-openjdk-amd64/bin/javac  /etc/alternatives/javac
java -version
javac -version
